services:
  express:
    build:
      context: ./
    ports:
      - '5155:5155'
      - '9229:9229'
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=express:*
    command:
      - nodemon
      - --inspect=0.0.0.0:9229
      - server.js